application: redditpicviewer
version: 1
runtime: python27
api_version: 1
threadsafe: true

  
libraries:

- name: django
  version: latest

handlers:
- url: /static
  static_dir: static
 
- url: /picviewer/static
  static_dir: picviewer/static
  
- url: /.*
  script: main.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'RedditViewer.settings'